service:
  name: note-taker-app

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    IMAGES_S3_BUCKET: note-taker-xyz-images-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 600 # in seconds


custom:
  serverless-offline:
    port: 3003

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: images/upload-url
          cors: true
  GetRecords:
    handler: src/lambda/http/getRecords.handler
    events:
      - http:
          method: get
          path: records
          cors: true



